[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "google"
src_paths = ["new"]
skip = ["__init__.py"]

[tool.mypy]
strict = true
allow_redefinition = true
